describe('Automate the Checkers game', () => {
  it('User make the multiple moves', () => {
    cy.visit('https://www.gamesforthebrain.com/game/checkers/')
    cy.get('[name="space42"]').click()
    cy.get('[name="space33"]').click()
    cy.wait(3000)
    cy.get('[name="space02"]').click()
    cy.get('[name="space13"]').click()
    cy.wait(3000)
    cy.get('[name="space51"]').click()
    cy.get('[name="space42"]').click()
    cy.wait(3000)
    cy.get('[name="space33"]').click()
    cy.get('[name="space55"]').click()
    cy.wait(3000)
    cy.get('[name="space62"]').click()
    cy.get('[name="space73"]').click()
    cy.wait(3000)
    cy.get('[href="./"]').click()
    cy.get('#message').should('have.text', 'Select an orange piece to move.')
  })
})